/**
 * Financial help for vet bills: Wisconsin and national programs.
 * Source: data/pet_financial_aid_orgs_expanded.xlsx (each row checked against the program's own site, Sep 26, 2026).
 * Payment financing (CareCredit, Cherry, VetBilling) is not in that sheet; it comes from WCVC's assistance page.
 *
 * Fields used by the matcher (aid.js):
 *   area      "national" | "wisconsin" | ["Dane", …]   where the owner must live
 *   levels    urgency levels (1–4) the program is for
 *   when      "now"    → can help before or at the visit
 *             "after"  → needs the vet's diagnosis + written estimate first; apply before paying
 *   income    "max60k" (≤ $60k/yr) | "fpl250" (< 250% of poverty line or government assistance) | "need" | null
 *   needCap   total need must be below this many dollars
 *   onlyAt    only for care at this clinic (name pattern)
 *   notAt     will not pay clinics whose name matches
 *   status    "open" | "paused" | "confirm" (details not re-checked: call first)
 */
export const AID_ORGS = [
  {
    id: "financing",
    name: "Payment plans: CareCredit, Cherry, VetBilling",
    kind: "financing",
    area: "national",
    levels: [1, 2, 3, 4],
    when: "now",
    income: null,
    amount: "Spread the bill over months",
    timing: "Same day at many clinics",
    pays: "A loan or payment plan. It is money you still owe, and lender approval applies.",
    docs: ["Ask the clinic which plans it accepts"],
    apply: "Ask at the front desk, or apply on the lender's site before the visit",
    url: "https://www.wicvc.org/financial-assistance",
    status: "open"
  },
  {
    id: "wiscares",
    name: "WisCARES",
    kind: "reduced-cost",
    area: ["Dane"],
    levels: [1, 2, 3],
    when: "now",
    income: "need",
    amount: "Reduced-cost or free care at their own clinic",
    timing: "Replies within about 72 hours",
    pays: "Care happens at the WisCARES clinic at a reduced cost.",
    docs: ["Income or housing information for a short phone questionnaire"],
    apply: "Call (608) 262-3950, option 4, or email. Not a walk-in clinic.",
    url: "https://wiscares.wisc.edu/",
    status: "open"
  },
  {
    id: "scaa",
    name: "Second Chance Animal Advocates",
    kind: "grant",
    area: ["Dane"],
    levels: [2, 3, 4],
    when: "now",
    income: "need",
    amount: "Varies",
    timing: "Online application",
    pays: "Helps with necessary and unexpected emergency care.",
    docs: ["Proof you live in Dane County", "What the care costs"],
    apply: "Online financial-aid application",
    url: "https://www.secondchanceanimaladvocates.org/s/SCAA-APPLICATION-FOR-FINANCIAL-AID-form-fill.pdf",
    status: "open"
  },
  {
    id: "hssw",
    name: "Humane Society of Southern Wisconsin: Sophie's Gift",
    kind: "grant",
    area: ["Rock"],
    areaNote: "Southern Wisconsin, Beloit-based: confirm they serve your area",
    levels: [1, 2, 3],
    when: "now",
    income: "need",
    amount: "Varies (vet bills and pet food)",
    timing: "Replies in 1–2 business days",
    pays: "Help goes through the clinic or program, not back to you.",
    docs: ["Read the program FAQ first", "Request form"],
    apply: "Online request form",
    url: "https://www.petsgohome.org/pet-services/community-assistance/",
    status: "open"
  },
  {
    id: "hh4p",
    name: "Helping Hands for Pets",
    kind: "grant",
    area: ["St. Croix", "Polk", "Pierce", "Dunn"],
    levels: [1, 2, 3],
    when: "now",
    income: "need",
    amount: "Varies; you may be asked to pay part",
    timing: "Mail or email application",
    pays: "Paid through its network of local vets.",
    docs: ["Printed application (one pet per application)"],
    apply: "Print, fill in, and send by email or mail",
    url: "https://helpinghands4pets.org/assistance",
    status: "open"
  },
  {
    id: "wi211",
    name: "211 Wisconsin",
    kind: "referral",
    area: "wisconsin",
    levels: [1, 2, 3, 4],
    when: "now",
    income: null,
    amount: "Referral to local county programs",
    timing: "Free call, any time",
    pays: "Not a fund: they point you to local help.",
    docs: [],
    apply: "Dial 211 or search online",
    url: "https://211wisconsin.communityos.org/",
    status: "confirm"
  },
  {
    id: "redrover",
    name: "RedRover Relief Urgent Care Grant",
    kind: "grant",
    area: "national",
    levels: [3, 4],
    when: "after",
    income: "max60k",
    needCap: 500,
    amount: "Usually $250–$300",
    timing: "Applications close Friday 4 p.m. Pacific and reopen Monday 9 a.m.",
    pays: "Paid to the vet hospital. No refunds for bills already paid.",
    docs: ["Diagnosis", "Treatment plan", "Written cost estimate", "Household income (≤ $60k/yr)"],
    apply: "Online pre-application, then the full application",
    url: "https://redrover.org/relief/urgent-care-grants/",
    status: "open",
    note: "Won't help if the total needed is $500 or more. One grant per household."
  },
  {
    id: "frankies",
    name: "Frankie's Friends National Fund",
    kind: "grant",
    area: "national",
    levels: [3, 4],
    when: "after",
    income: "fpl250",
    amount: "Up to $2,000",
    timing: "Online application",
    pays: "Paid to the treating hospital. No refunds for money already spent.",
    docs: ["Diagnosis", "Treatment plan", "Written cost estimate", "Proof of government assistance or income below 250% of the poverty line"],
    apply: "Online application",
    url: "https://www.frankiesfriends.org/national-frankies-friends-fund",
    status: "open",
    notAt: "Banfield|VCA|BluePearl",
    note: "Doesn't cover the first exam or tests, and won't pay hospitals with their own aid programs (Banfield, VCA, BluePearl)."
  },
  {
    id: "paws4acure",
    name: "Paws 4 A Cure",
    kind: "grant",
    area: "national",
    levels: [3, 4],
    when: "after",
    income: "need",
    amount: "Up to $400, one time",
    timing: "Owner applies, then the vet sends its packet",
    pays: "The vet sends an itemized invoice after treatment and is paid directly.",
    docs: ["Diagnosis", "Treatment plan", "Proof of financial hardship", "Vet packet (the clinic fills this in)"],
    apply: "Online application with hardship documents",
    url: "https://www.paws4acure.org/askforhelp.php",
    status: "open",
    note: "The clinic must agree to work with the nonprofit."
  },
  {
    id: "bowwow",
    name: "Bow Wow Buddies Foundation",
    kind: "grant",
    area: "national",
    levels: [3, 4],
    when: "after",
    income: null,
    amount: "Up to $1,500 (about $1,100 on average)",
    timing: "Reviewed on the 1st and 15th",
    pays: "Paid to the vet hospital.",
    docs: ["Diagnosis", "Written cost estimate", "Photo of your dog"],
    apply: "Online application",
    url: "https://www.bowwowbuddies.com/apply-for-grant/",
    status: "paused",
    note: "Applications are paused on their site right now. Check before counting on it."
  },
  {
    id: "petfund",
    name: "The Pet Fund",
    kind: "grant",
    area: "national",
    levels: [1, 2],
    when: "after",
    income: "need",
    amount: "Varies",
    timing: "Email first; they tell you the wait-list time",
    pays: "Paid to the vet after approval.",
    docs: ["Email describing the medical situation (before applying)", "Diagnosis", "Written cost estimate"],
    apply: "Email first, then apply only when they say to",
    url: "https://www.thepetfund.com/",
    status: "open",
    note: "Only for non-urgent, non-routine care. Excludes emergencies."
  },
  {
    id: "respond",
    name: "UW Veterinary Care RESPOND Fund",
    kind: "grant",
    area: "wisconsin",
    levels: [3, 4],
    when: "after",
    income: "need",
    amount: "Up to $2,500, one time",
    timing: "Through UW Veterinary Care staff",
    pays: "A credit on your UW Veterinary Care bill.",
    docs: ["Active UW Veterinary Care client", "Financial need (reviewed by their staff)"],
    apply: "Ask the UW Veterinary Care financial counselor",
    url: "https://www.vetmed.wisc.edu/giving/respond-fund/",
    status: "open",
    onlyAt: "UW Veterinary Care",
    note: "Only for UW Veterinary Care patients who are seriously ill or injured."
  },
  {
    id: "wcvc",
    name: "WCVC Veterinary Assistance Program",
    kind: "grant",
    area: "wisconsin",
    levels: [2, 3],
    when: "after",
    income: "need",
    amount: "Varies by case",
    timing: "Contact the clinic",
    pays: "A discount on your WCVC bill. Care must be at a WCVC clinic.",
    docs: ["Estimate from a WCVC vet"],
    apply: "Contact WCVC to start the application",
    url: "https://www.wicvc.org/financial-assistance",
    status: "confirm",
    onlyAt: "Wisconsin Community Veterinary|WCVC",
    note: "Award amounts not re-checked: call to confirm."
  },
  {
    id: "heart2heart",
    name: "Heart2Heart Pet Lifeline",
    kind: "grant",
    area: ["La Crosse"],
    levels: [1, 2, 3],
    when: "after",
    income: "need",
    amount: "Vet grants up to $500 ($25 copay)",
    timing: "Application through Coulee Region Humane Society",
    pays: "Paid to the vet, never to you.",
    docs: ["Diagnosis", "Treatment plan", "Written cost estimate", "Proof of financial need"],
    apply: "Application with the required documents",
    url: "https://www.heart2heartpet.org/grants",
    status: "open"
  },
  {
    id: "noahs",
    name: "Noah's Animal Fund",
    kind: "grant",
    area: ["Rock", "Jefferson", "Green", "Walworth"],
    levels: [3, 4],
    when: "after",
    income: "need",
    amount: "Up to $500",
    timing: "Owner applies; the vet fills in a medical form",
    pays: "Toward approved medical procedures.",
    docs: ["Application", "Veterinary Medical Form (the clinic fills this in)"],
    apply: "Online or downloadable application",
    url: "https://www.friendsofnoah-wi.org/noahs-animal-fund",
    status: "open",
    note: "Treatment must have a reasonable chance of success. No routine care."
  }
];
