/** Clinic-published Wisconsin prices. Amounts were copied from each clinic page on 2026-09-26. Coordinates are OpenStreetMap address points. */

const ACCESSED = "2026-09-26";

function clinic(fields) {
  return { state: "WI", careType: "general", hours: "", website: "", dayOffset: 0, ...fields };
}

function price(fields) {
  return {
    evidence: "clinicPosted",
    confidence: "HIGH",
    medianPrice: null,
    publishedDate: null,
    restrictions: "",
    accessedDate: ACCESSED,
    ...fields,
    highPrice: fields.priceType === "starting-at" ? null : fields.highPrice ?? fields.lowPrice
  };
}

export const clinics = [
  clinic({ id: "precision", name: "Precision Veterinary Madison", address: "6107 Odana Rd, Madison, WI 53719", city: "Madison", zip: "53719", lat: 43.05352, lng: -89.486853, phone: "(608) 405-3148", website: "https://precisionveterinary.com/services/", hours: "Mon–Fri 7:00 AM – 6:00 PM", dayOffset: 0 }),
  clinic({ id: "banfield-east", name: "Banfield Pet Hospital — Madison East", address: "2216 E Springs Dr, Madison, WI 53704", city: "Madison", zip: "53704", lat: 43.1284884, lng: -89.2964673, phone: "(608) 243-1649", website: "https://www.banfield.com/locations/veterinarians/wi/madison/emn/service-pricing", hours: "Mon–Thu 8 AM – 6 PM; Fri 8 AM – 5 PM; Sat–Sun hours vary", dayOffset: 1 }),
  clinic({ id: "banfield-west", name: "Banfield Pet Hospital — Madison West", address: "8210 Plaza Dr, Madison, WI 53719", city: "Madison", zip: "53719", lat: 43.0570862, lng: -89.5246556, phone: "(608) 826-6255", website: "https://www.banfield.com/locations/veterinarians/wi/madison/mdw/service-pricing", hours: "Mon–Fri 8 AM – 6 PM; Sat 8 AM – 5 PM; Sun 8 AM – 4 PM", dayOffset: 1 }),
  clinic({ id: "underdog", name: "Underdog Vet Services", address: "2508 S Stoughton Road, Madison, WI 53716", city: "Madison", zip: "53716", lat: 43.058836, lng: -89.3096375, phone: "(608) 268-7060", website: "https://www.underdogpetrescue.org/vet-clinic", hours: "Mon–Thu 7:45 AM – 6:30 PM; Fri 7:45 AM – 5:00 PM. Urgent walk-in Mon–Fri 1–5 PM.", careType: "urgent", dayOffset: 0 }),
  clinic({ id: "truesdell", name: "Truesdell Animal Care Hospital and Clinic", address: "4214 Milwaukee Street, Madison, WI 53714", city: "Madison", zip: "53714", lat: 43.0985876, lng: -89.3126628, phone: "(608) 244-2555", website: "https://www.trueanimalcare.com/new-client-information/", hours: "Mon–Fri daytime; Sat morning. See the clinic page.", dayOffset: 1 }),
  clinic({ id: "wcvc", name: "Wisconsin Community Veterinary Center", address: "4475 Robertson Rd, Madison, WI 53714", city: "Madison", zip: "53714", lat: 43.0909834, lng: -89.3080214, phone: "(608) 224-1400", website: "https://www.wicvc.org/wellness", hours: "See the clinic page.", careType: "wellness", dayOffset: 2 }),
  clinic({ id: "veg", name: "VEG Madison", address: "7456 Mineral Point Road, Madison, WI 53717", city: "Madison", zip: "53717", lat: 43.0606666, lng: -89.5120393, phone: "(608) 716-3255", website: "https://www.veg.com/locations/wisconsin/madison", hours: "24/7", careType: "emergency", dayOffset: 0 }),
  clinic({ id: "new-berlin", name: "New Berlin Animal Hospital", address: "3840 S Moorland Rd, New Berlin, WI 53151", city: "New Berlin", zip: "53151", lat: 42.9743105, lng: -88.1078616, phone: "(262) 782-6910", website: "https://newberlinanimalhospital.com/service-pricing/", hours: "Mon–Fri 7:30 AM – 5:00 PM; Sat 8:00 AM – 12:00 PM", dayOffset: 2 }),
  clinic({ id: "haws", name: "HAWS Wellness Clinic", address: "701 Northview Road, Waukesha, WI 53188", city: "Waukesha", zip: "53188", lat: 43.031762, lng: -88.2328171, phone: "(262) 542-8852", website: "https://hawspets.org/wellness-clinic/", hours: "Wellness is offered 5 days a week. Schedule through the SNIP clinic.", careType: "wellness", dayOffset: 2 }),
  clinic({ id: "badger", name: "Badger Veterinary Hospital", address: "3113 E. McCormick Drive, Janesville, WI 53547", city: "Janesville", zip: "53547", lat: 42.7394722, lng: -88.9787, phone: "(608) 754-1888", website: "https://www.badgervet.com/site/book-online", hours: "Mon–Fri 8:00 AM – 6:00 PM; Sat 8:00 AM – 2:00 PM", dayOffset: 1 }),
  clinic({ id: "delavan", name: "Delavan Lakes Veterinary Clinic", address: "1107 Ann St, Delavan, WI 53115", city: "Delavan", zip: "53115", lat: 42.6327402, lng: -88.6295656, phone: "(262) 728-8622", website: "https://delavanlakesvet.com/service-pricing/", hours: "Mon–Fri 7:30 AM – 5:00 PM; Sat 7:30 AM – 12:00 PM. Urgent care available.", careType: "urgent", dayOffset: 2 }),
  clinic({ id: "geneva", name: "Geneva Lakes Animal Hospital", address: "100 Ridge Rd, Walworth, WI 53184", city: "Walworth", zip: "53184", lat: 42.5306653, lng: -88.5841649, phone: "(262) 275-3303", website: "https://genevalakesanimalhospital.com/service-pricing/", hours: "Mon, Wed, Thu, Fri 8:00 AM – 5:00 PM; Tue 8:00 AM – 6:00 PM; Sat 8:00 AM – 12:00 PM", dayOffset: 3 }),
  clinic({ id: "ashwaubenon", name: "CareVet of Ashwaubenon", address: "1030 Willard Dr, Green Bay, WI 54304", city: "Green Bay", zip: "54304", lat: 44.4893473, lng: -88.0727453, phone: "(920) 499-0805", website: "https://ash-vet.com/service-pricing/", hours: "Mon–Fri 8:00 AM – 6:00 PM", dayOffset: 1 }),
  clinic({ id: "oconto", name: "CareVet of Oconto Falls", address: "180 E Highland Dr, Oconto Falls, WI 54154", city: "Oconto Falls", zip: "54154", lat: 44.8823013, lng: -88.1429217, phone: "(920) 848-4280", website: "https://www.carevet.com/oconto-falls/service-pricing/", hours: "Mon–Thu 7:30 AM – 6:00 PM; Fri 7:30 AM – 5:00 PM", dayOffset: 2 }),
  clinic({ id: "northern", name: "Northern Paws Animal Hospital", address: "1175 Lincoln St, Rhinelander, WI 54501", city: "Rhinelander", zip: "54501", lat: 45.6349444, lng: -89.3932417, phone: "(715) 369-4900", website: "https://northernpawsanimalhospital.com/service-pricing/", hours: "Mon–Fri 8:00 AM – 5:00 PM. Some Saturdays; call to confirm.", dayOffset: 3 })
];

export const pricingRecords = [
  price({ id: "precision-routine-exam", service: "routineExam", serviceLabel: "Routine exam", lowPrice: "55", priceType: "starting-at", clinicID: "precision", clinicName: "Precision Veterinary Madison", sourceName: "Precision Veterinary Madison", sourceTitle: "Services & Pricing", sourceURL: "https://precisionveterinary.com/services/", notes: "Published as routine exams starting at $55. No upper price is published." }),
  price({ id: "precision-medical-concern", service: "medicalConcernExam", serviceLabel: "Medical-concern appointment", lowPrice: "75", priceType: "fixed", clinicID: "precision", clinicName: "Precision Veterinary Madison", sourceName: "Precision Veterinary Madison", sourceTitle: "Services & Pricing", sourceURL: "https://precisionveterinary.com/services/", notes: "Published as a medical-concern appointment price." }),
  price({ id: "precision-fecal", service: "fecalExam", serviceLabel: "Fecal test", lowPrice: "25", priceType: "fixed", clinicID: "precision", clinicName: "Precision Veterinary Madison", sourceName: "Precision Veterinary Madison", sourceTitle: "Services & Pricing", sourceURL: "https://precisionveterinary.com/services/", notes: "Published on the add-on list. The clinic asks clients to bring a stool sample." }),
  price({ id: "precision-ear-cleaning", service: "earCleaning", serviceLabel: "Ear cleaning", lowPrice: "20", priceType: "fixed", clinicID: "precision", clinicName: "Precision Veterinary Madison", sourceName: "Precision Veterinary Madison", sourceTitle: "Services & Pricing", sourceURL: "https://precisionveterinary.com/services/", notes: "Listed at $20. Free for surgical patients in recovery." }),
  price({ id: "precision-preop-bloodwork", service: "preoperativeBloodwork", serviceLabel: "Pre-operative bloodwork", lowPrice: "65", priceType: "fixed", clinicID: "precision", clinicName: "Precision Veterinary Madison", sourceName: "Precision Veterinary Madison", sourceTitle: "Services & Pricing", sourceURL: "https://precisionveterinary.com/services/", notes: "Dental-section bloodwork at $65. This is not a diagnostic CBC." }),
  price({ id: "banfield-east-office-visit", service: "officeVisit", serviceLabel: "Office visit", lowPrice: "76.95", priceType: "fixed", clinicID: "banfield-east", clinicName: "Banfield Pet Hospital — Madison East", sourceName: "Banfield Pet Hospital — Madison East", sourceTitle: "Cost of care at Madison", sourceURL: "https://www.banfield.com/locations/veterinarians/wi/madison/emn/service-pricing", publishedDate: "2025-05-14", notes: "Banfield labels this as an estimate and says pricing may vary. An additional office-visit fee is required for other services, including vaccines." }),
  price({ id: "banfield-west-office-visit", service: "officeVisit", serviceLabel: "Office visit", lowPrice: "76.95", priceType: "fixed", clinicID: "banfield-west", clinicName: "Banfield Pet Hospital — Madison West", sourceName: "Banfield Pet Hospital — Madison West", sourceTitle: "Cost of care at Madison W", sourceURL: "https://www.banfield.com/locations/veterinarians/wi/madison/mdw/service-pricing", publishedDate: "2025-05-14", notes: "Banfield labels this as an estimate and says pricing may vary. An additional office-visit fee is required for other services, including vaccines." }),
  price({ id: "underdog-urgent-exam", service: "urgentExam", serviceLabel: "Urgent-care walk-in exam", lowPrice: "85", priceType: "fixed", clinicID: "underdog", clinicName: "Underdog Vet Services", sourceName: "Underdog Vet Services", sourceTitle: "Underdog Vet Services", sourceURL: "https://www.underdogpetrescue.org/vet-clinic", notes: "Exam fee for urgent-care walk-ins, Monday–Friday 1–5 p.m., first come, first served." }),
  price({ id: "truesdell-new-client-exam", service: "newClientExam", serviceLabel: "New-client first comprehensive exam", lowPrice: "38", priceType: "fixed", clinicID: "truesdell", clinicName: "Truesdell Animal Care Hospital and Clinic", sourceName: "Truesdell Animal Care Hospital and Clinic", sourceTitle: "New Client Information", sourceURL: "https://www.trueanimalcare.com/new-client-information/", restrictions: "New clients only. Mention the offer at or before checkout the same day. Cannot be combined with other discounts.", notes: "New clients’ first comprehensive exam." }),
  price({ id: "wcvc-routine-wellness", service: "routineExam", serviceLabel: "Routine wellness visit", lowPrice: "40", priceType: "fixed", clinicID: "wcvc", clinicName: "Wisconsin Community Veterinary Center", sourceName: "Wisconsin Community Veterinary Center", sourceTitle: "Wellness", sourceURL: "https://www.wicvc.org/wellness", publishedDate: "2026-09-21", notes: "Dog routine wellness visit. The page says prices are current as of September 21, 2026." }),
  price({ id: "wcvc-sick-wellness", service: "medicalConcernExam", serviceLabel: "Sick/injured urgent wellness visit", lowPrice: "60", priceType: "fixed", clinicID: "wcvc", clinicName: "Wisconsin Community Veterinary Center", sourceName: "Wisconsin Community Veterinary Center", sourceTitle: "Wellness", sourceURL: "https://www.wicvc.org/wellness", publishedDate: "2026-09-21", notes: "Dog sick/injured urgent wellness visit. The page says prices are current as of September 21, 2026." }),
  price({ id: "new-berlin-wellness", service: "routineExam", serviceLabel: "Wellness exam", lowPrice: "98", priceType: "fixed", clinicID: "new-berlin", clinicName: "New Berlin Animal Hospital", sourceName: "New Berlin Animal Hospital", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://newberlinanimalhospital.com/service-pricing/", notes: "Head-to-tail wellness exam. Tax is not included." }),
  price({ id: "new-berlin-sick", service: "medicalConcernExam", serviceLabel: "Sick exam", lowPrice: "121", priceType: "fixed", clinicID: "new-berlin", clinicName: "New Berlin Animal Hospital", sourceName: "New Berlin Animal Hospital", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://newberlinanimalhospital.com/service-pricing/", notes: "Same-day appointment for a pet who is not feeling well. Tax is not included." }),
  price({ id: "haws-physical", service: "routineExam", serviceLabel: "Physical exam", lowPrice: "30", priceType: "fixed", clinicID: "haws", clinicName: "HAWS Wellness Clinic", sourceName: "HAWS", sourceTitle: "Wellness Clinic", sourceURL: "https://hawspets.org/wellness-clinic/", restrictions: "The clinic says it is prioritizing wellness appointments for people receiving government assistance.", notes: "Published as Physical Exam = $30." }),
  price({ id: "haws-sick", service: "medicalConcernExam", serviceLabel: "Sick exam", lowPrice: "45", priceType: "fixed", clinicID: "haws", clinicName: "HAWS Wellness Clinic", sourceName: "HAWS", sourceTitle: "Wellness Clinic", sourceURL: "https://hawspets.org/wellness-clinic/", restrictions: "Nonprofit wellness clinic. Wellness appointments are prioritized for people receiving government assistance.", notes: "Published as Sick Exam = $45." }),
  price({ id: "badger-new-client", service: "newClientExam", serviceLabel: "New-client first routine exam", lowPrice: "25", priceType: "fixed", clinicID: "badger", clinicName: "Badger Veterinary Hospital", sourceName: "Badger Veterinary Hospital", sourceTitle: "Book Online", sourceURL: "https://www.badgervet.com/site/book-online", restrictions: "New clients. Dogs or cats. Applies only to the exam fee, not other services, emergency, or specialty care. One per household. Cannot be combined with other promotions.", notes: "Published as a $25 first routine exam for new clients." }),
  price({ id: "delavan-wellness", service: "routineExam", serviceLabel: "Wellness exam", lowPrice: "71", priceType: "fixed", clinicID: "delavan", clinicName: "Delavan Lakes Veterinary Clinic", sourceName: "Delavan Lakes Veterinary Clinic", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://delavanlakesvet.com/service-pricing/", notes: "Head-to-tail wellness exam. Tax is not included." }),
  price({ id: "delavan-urgent", service: "urgentExam", serviceLabel: "Urgent care exam", lowPrice: "115", priceType: "fixed", clinicID: "delavan", clinicName: "Delavan Lakes Veterinary Clinic", sourceName: "Delavan Lakes Veterinary Clinic", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://delavanlakesvet.com/service-pricing/", notes: "Same-day appointment for a pet who is not feeling well. Tax is not included." }),
  price({ id: "geneva-wellness", service: "routineExam", serviceLabel: "Wellness exam", lowPrice: "72", priceType: "fixed", clinicID: "geneva", clinicName: "Geneva Lakes Animal Hospital", sourceName: "Geneva Lakes Animal Hospital", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://genevalakesanimalhospital.com/service-pricing/", notes: "Head-to-tail wellness exam. Tax is not included." }),
  price({ id: "geneva-urgent", service: "urgentExam", serviceLabel: "Urgent care exam", lowPrice: "148", priceType: "fixed", clinicID: "geneva", clinicName: "Geneva Lakes Animal Hospital", sourceName: "Geneva Lakes Animal Hospital", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://genevalakesanimalhospital.com/service-pricing/", notes: "Same-day appointment for a pet who is not feeling well. Tax is not included." }),
  price({ id: "ashwaubenon-urgent", service: "urgentExam", serviceLabel: "Urgent care exam", lowPrice: "112", priceType: "fixed", clinicID: "ashwaubenon", clinicName: "CareVet of Ashwaubenon", sourceName: "CareVet of Ashwaubenon", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://ash-vet.com/service-pricing/", notes: "Same-day appointment for a pet who is not feeling well. Tax is not included." }),
  price({ id: "ashwaubenon-emergency", service: "emergencyExam", serviceLabel: "Walk-in emergency visit", lowPrice: "162", priceType: "fixed", clinicID: "ashwaubenon", clinicName: "CareVet of Ashwaubenon", sourceName: "CareVet of Ashwaubenon", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://ash-vet.com/service-pricing/", notes: "Published in parentheses as walk-in emergency visits $162, next to the urgent care exam. Tax is not included." }),
  price({ id: "oconto-wellness", service: "routineExam", serviceLabel: "Wellness exam", lowPrice: "76", priceType: "fixed", clinicID: "oconto", clinicName: "CareVet of Oconto Falls", sourceName: "CareVet of Oconto Falls", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://www.carevet.com/oconto-falls/service-pricing/", notes: "Head-to-tail wellness exam. Tax is not included. No sick or urgent exam price is published on this page." }),
  price({ id: "northern-wellness", service: "routineExam", serviceLabel: "Wellness exam", lowPrice: "81", priceType: "fixed", clinicID: "northern", clinicName: "Northern Paws Animal Hospital", sourceName: "Northern Paws Animal Hospital", sourceTitle: "Veterinary Service Pricing", sourceURL: "https://northernpawsanimalhospital.com/service-pricing/", notes: "Head-to-tail wellness exam. Tax is not included. No sick or urgent exam price is published on this page." })
];
